# CNET Agent Configuration

agent:
  address: "0.0.0.0"
  port: 8080
  node_id: "discovery-server"
  node_name: "Discovery Server"
  region: "default"
  datacenter: "dc1"
  heartbeat: "30s"

logging:
  level: "info"  # debug, info, warn, error
  format: "json"  # json, text

discovery:
  enabled: true  # Enable discovery for root server
  servers: []  # No discovery servers for root node
  timeout: "5s"
  retry: 3

resources:
  cpu: true
  memory: true
  disk: true
  network: true
  interval: "10s"

tasks:
  max_concurrent: 10
  timeout: "5m"
  cleanup: true

ml:
  enabled: true
  engines: ["python", "tensorflow", "pytorch"]
  default_engine: "python"
  model_path: "./models"
  script_path: "./examples/ml_models"
  port_range:
    start: 9000
    end: 9100
  resource_limits:
    cpu_limit: 1.0
    memory_limit: 536870912  # 512MB
    disk_limit: 1073741824   # 1GB
    gpu_limit: 0
  timeout: "30s"
