# CNET Agent 配置文件

# Agent基础配置
agent:
  node_id: "agent-1"
  address: "0.0.0.0"
  port: 8080

# 本地资源配置
resources:
  cpu: 4.0          # CPU核心数
  gpu: 0            # GPU数量
  memory: 8589934592    # 8GB 内存（字节）
  storage: 107374182400 # 100GB 存储（字节）

# 父节点配置（层次化架构）
parent:
  enabled: false
  address: "parent-agent:8080"

# Peer节点配置（对等架构）
peers:
  enabled: false
  addresses:
    - "peer-1:8080"
    - "peer-2:8080"

# 日志配置
logging:
  level: "info"  # debug, info, warn, error
  format: "json" # json, text

