version: '3.8'

services:
  cnet-agent:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CNET_LOG_LEVEL=info
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Example discovery server (optional)
  discovery-server:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
