# 子节点配置示例

agent:
  node_id: "child-agent-1"
  address: "0.0.0.0"
  port: 8081

resources:
  cpu: 4.0
  gpu: 0
  memory: 8589934592     # 8GB
  storage: 107374182400  # 100GB

# 注册到父节点
parent:
  enabled: true
  address: "localhost:8080"

peers:
  enabled: false

logging:
  level: "info"
  format: "text"

