# 江苏省节点配置

agent:
  node_id: "jiangsu"
  address: "0.0.0.0"
  port: 8080

resources:
  cpu: 0.5               # 很少的CPU，故意不足
  gpu: 0
  memory: 536870912      # 512MB，资源不足
  storage: 10737418240   # 10GB

parent:
  enabled: false

peers:
  enabled: false

logging:
  level: "info"
  format: "text"

