agent:
  address: "0.0.0.0"
  port: 8082
  node_id: "level2-node"
  node_name: "Level 2 Node"
  region: "us-west"
  datacenter: "dc1"
  heartbeat: "30s"

logging:
  level: "info"
  format: "json"

discovery:
  enabled: true
  servers:
    - "localhost:8080"  # 向根节点注册
  timeout: "5s"
  retry: 3

resources:
  cpu: true
  memory: true
  disk: true
  network: true
  interval: "10s"

tasks:
  max_concurrent: 10
  timeout: "5m"
  cleanup: true
