# 南京市节点配置

agent:
  node_id: "nanjing"
  address: "0.0.0.0"
  port: 8081

resources:
  cpu: 8.0               # 充足的CPU资源
  gpu: 1                 # 有GPU
  memory: 17179869184    # 16GB，充足的内存
  storage: 214748364800  # 200GB

# 注册到父节点
parent:
  enabled: true
  address: "localhost:8080"

# 配置peer节点
peers:
  enabled: true
  addresses:
    - "localhost:8082"  # peer-agent-1
    - "localhost:8083"  # peer-agent-2

logging:
  level: "info"
  format: "text"

