# 父节点配置示例

agent:
  node_id: "parent-agent"
  address: "0.0.0.0"
  port: 8080

resources:
  cpu: 8.0
  gpu: 1
  memory: 17179869184    # 16GB
  storage: 214748364800  # 200GB

parent:
  enabled: false

peers:
  enabled: false

logging:
  level: "info"
  format: "text"

