agent:
  address: "0.0.0.0"
  port: 8080
  node_id: "discovery-server"
  node_name: "Discovery Server"
  region: "us-west"
  datacenter: "dc1"
  heartbeat: "30s"

logging:
  level: "info"
  format: "json"

discovery:
  enabled: false  # 作为发现服务器，不需要向其他服务器注册
  servers: []
  timeout: "5s"
  retry: 3

resources:
  cpu: true
  memory: true
  disk: true
  network: true
  interval: "10s"

tasks:
  max_concurrent: 10
  timeout: "5m"
  cleanup: true
